spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: student-service
        uri: http://localhost:9001
        predicates:
        - Path=/api/v1/students/**
server:
  port: 8080
